### ISSUE TITLE
Cool, where is the code?

### ISSUE THREAD

**Issue by Green-Sky** [tpecholt/imrad#1]
Looks like a very cool very useful project, but why is there no source code?

**Comment by tpecholt** [comment]
Thanks for the interest! I will push the code in the near future. I just need to polish it a bit and choose the right license. Until then you can of course use the released version to generate GUI code and use it in any project without restriction.

**Comment by Green-Sky** [comment]
Nice!
Since this is not a library, something "restrictive" like GPL would be ok.

**Comment by tpecholt** [comment]
code pushed
