### ISSUE TITLE
License Change Suggestion

### ISSUE THREAD

**Issue by uventura** [tpecholt/imrad#24]
Hi! Currently I intend to change ImRad a little, but I would like to know if it's possible to change the license to MIT (the same license that ImGui uses). I respect and understand if not.

**Comment by tpecholt** [comment]
Hi. I don't currently plan to change the license. I don't see enough reasons to do that

**Comment by uventura** [comment]
Ok, no problem, I was asking because I plan to change the software structure. Usually MIT license is good if you want the software to be fully free about the usage, for me it's ok to be GPL-3.

**Comment by uventura** [comment]
Thanks for the feedback!
