### ISSUE TITLE
Build error Windows

### ISSUE THREAD

**Issue by oktonion** [tpecholt/imrad#25]
Hello

Build on windows from VS 2019 cmd with:

```cmd
cmake -B ./ -DCMAKE_BUILD_TYPE=Release
cmake --build ./ --config Release --parallel 8
```

gives this error:

> Building Custom Rule C:/Users/User/Documents/GitHub/imrad/CMakeLists.t
> xt
> CMake does not need to re-run because C:/Users/User/Documents/GitHub/i
> mrad/CMakeFiles/generate.stamp is up-to-date.
> No download step for 'nativefiledialog'
> No update step for 'nativefiledialog'
> No patch step for 'nativefiledialog'
> Performing configure step for 'nativefiledialog'
> loading initial cache file C:/Users/User/Documents/GitHub/imrad/3rdpar
> ty/nativefiledialog/tmp/nativefiledialog-cache-Release.cmake
> -- Selecting Windows SDK version 10.0.18362.0 to target Windows 6.1.76
> 01.
> nfd Platform: PLATFORM_WIN32
> nfd Compiler: COMPILER_MSVC
> CMake Error at src/CMakeLists.txt:127 (install):
>   install TARGETS given no ARCHIVE DESTINATION for static library targ
> et
>   "nfd".

What am I doing wrong there?

**Comment by tpecholt** [comment]
Can you try to upgrade tour cmake? It seems it helped to people with similar issue
