### ISSUE TITLE
Can't generate created layout

### ISSUE THREAD

**Issue by colesnicov** [tpecholt/imrad#29]
Hello.

OS: Ubuntu
CPU: AMD64

I can't save the file:

```denis@denis-OMEN:~/opt/imrad2/install/imrad-0.7$ ./imrad 
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot get file time: Directory or file does not exist [/home/denis/opt/imrad2/install/imrad-0.7/test.h]
Exit failed (SIGABRT) (core dumped [dump memory saved])
```

### Procedure:

- I will create a new window
- `CTRL+S`
- Type name `test`
- Enter Save

_You can see the result above_

---------------------------------

### Solution:

It only works for me like **su**:

```
sudo ./imrad
```

**Comment by colesnicov** [comment]
For those who do not want this application to allow superuser permissions, reset all file permissions first. Some file probably has the ``root'' role set and then asks for the superuser password and then can do mischief.. Be careful friends, I'm not that knowledgeable in this area, but I don't like this behavior!

https://github.com/tpecholt/imrad/issues/28

**Comment by tpecholt** [comment]
I can't reproduce this and ImRAD runs without sudo on my ubuntu. 

However if for some reason entered path can't be written to there was a crash. I added an error message box instead.
