### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by jvdnbus** [tpecholt/imrad#36]
I've been unable to build the project after several hours of trying. Freetype seems to have made it considerably more cumbersome to build as it requires several building blocks (harfbuzz, ...) and these are quite annoying to build on Windows. The build was successful at first but none of the icons worked alas (appeared as "?").

Do you have any ETA on a new release with binaries included?

**Comment by tpecholt** [comment]
Sorry to hear that. Did you try to build freetype on your own? Harfbuzz and other features should be disabled see 3rdparty/freetype.cmake. Not sure why that didn't work for you.

I want to release new version this month so stay tuned.

**Comment by jvdnbus** [comment]
So I started over and tried again and this time everything works fine. I'm not sure what I did differently or what happened unfortunately. Guess I'll mark this as resolved :)
