### ISSUE TITLE
Button `nextColumn` parameter decrementing from 0 will freeze the program

### ISSUE THREAD

**Issue by MaKiPL** [tpecholt/imrad#37]
There's a reproducable program freeze when tweaking the `nextColumn` parameter on Button (and probably other controls).

1. Put button on layout
2. Scroll to `nextColumn` parameter. It should show 0 by default
3. Click on `-` to decrement the value
4. Observer the program freezing

**Comment by tpecholt** [comment]
Thanks for reporting it.
